# Set update schedule for GitHub Actions

version: 2
updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      # Check for updates to GitHub Actions every week
    interval: "weekly"
- package-ecosystem: "nuget"
  directory: "/"
  schedule:
      # Check for updates to NuGet packages every week
    interval: "weekly"
