name: CI

on:
  push:
  release:
    types: [created]
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: set up dotnet core 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0
    - name: publish
      run: dotnet publish -c Release /p:Platform="Any CPU" -o --framework=net6.0 abb_robotraconteur_driver
    - name: copy license and readme
      run: |
         Copy-Item -Path LICENSE.txt -Destination abb_robotraconteur_driver
         Copy-Item -Path README.md -Destination abb_robotraconteur_driver
    - name: zip
      run: Compress-Archive -Path abb_robotraconteur_driver -DestinationPath abb_robotraconteur_driver.zip
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: abb_robotraconteur_driver
        path: abb_robotraconteur_driver.zip